### ISSUE TITLE
List public DockerHub repositories and tags by namespace

### ISSUE THREAD

**Issue by hebestreit** [turbot/steampipe-plugin-dockerhub#24]
**Is your feature request related to a problem? Please describe.**
Initially when we saw this plugin we thought that it's capable of querying information from all publicly available repositories on DockerHub. Unfortunately we discovered that you can only list repositories or tags which are owned by the authenticated user.

Our current need is to join the [dockerhub_tag](https://hub.steampipe.io/plugins/turbot/dockerhub/tables/dockerhub_tag) table on `container_image` from the [kubernetes_pod](https://hub.steampipe.io/plugins/turbot/kubernetes/tables/kubernetes_pod) table so that we can view the latest pushed Docker image tags for all workloads running in our Kubernetes cluster.

**Describe the solution you'd like**
Instead of passing the user's account name to the `client.GetRepositories(user.Name)` function we could introduce a new column called `namespace` which can be used inside the `where` clause. 

As DockerHub doesn't provide the possibility to query repositories of all namespaces one always need to specify one or multiple namespaces. In case it's not defined we will retain the current behavior to get this information from the authenticated user to also not introduce breaking changes.

I derived the name `namespace` for the newly introduced column from the DockerHub API specs:

https://docs.docker.com/reference/api/hub/latest/#tag/repositories/paths/~1v2~1namespaces~1%7Bnamespace%7D~1repositories~1%7Brepository%7D~1tags/get

**Describe alternatives you've considered**
There are no alternatives as the user name is "hard-coded".

**Additional context**

### Example to list repositories in the "turbot" namespace

```sql
select
    name,
    pull_count,
    star_count,
    is_private,
    last_updated
from
    dockerhub_repository
where 
    namespace = 'turbot';
``` 

```
+------------------+------------+------------+------------+---------------------------+
| name             | pull_count | star_count | is_private | last_updated              |
+------------------+------------+------------+------------+---------------------------+
| turbot/steampipe | 102933     | 6          | false      | 2024-03-15T11:24:26+01:00 |
+------------------+------------+------------+------------+---------------------------+
```

### Example to list tags of the "steampipe" image in the "turbot" namespace

```sql
select
    name,
    status,
    last_updater_user_name,
    last_pushed,
    last_pulled,
    full_size
from
    dockerhub_tag
where 
  namespace = 'turbot'
  and name like 'turbot/steampipe:0.21%';
``` 

```
+-------------------------+----------+------------------------+---------------------------+---------------------------+-----------+
| name                    | status   | last_updater_user_name | last_pushed               | last_pulled               | full_size |
+-------------------------+----------+------------------------+---------------------------+---------------------------+-----------+
| turbot/steampipe:0.21.0 | active   | kaidaguerre            | 2023-10-02T13:41:30+02:00 | 2024-09-03T09:20:42+02:00 | 117338375 |
| turbot/steampipe:0.21.2 | inactive | kaidaguerre            | 2023-12-12T16:31:11+01:00 | 2024-07-30T06:09:34+02:00 | 103223967 |
| turbot/steampipe:0.21.1 | inactive | kaidaguerre            | 2023-10-03T17:11:26+02:00 | 2024-07-30T06:16:38+02:00 | 117339696 |
| turbot/steampipe:0.21.3 | inactive | kaidaguerre            | 2024-01-05T16:24:00+01:00 | 2024-06-03T11:57:34+02:00 | 103435655 |
| turbot/steampipe:0.21.8 | inactive | kaidaguerre            | 2024-02-23T15:36:00+01:00 | 2024-07-30T06:16:17+02:00 | 103282153 |
| turbot/steampipe:0.21.6 | active   | kaidaguerre            | 2024-02-06T13:33:56+01:00 | 2024-08-25T02:00:05+02:00 | 103245103 |
| turbot/steampipe:0.21.7 | active   | kaidaguerre            | 2024-02-09T18:01:01+01:00 | 2024-09-03T05:42:59+02:00 | 103073197 |
| turbot/steampipe:0.21.5 | inactive | kaidaguerre            | 2024-02-05T18:57:41+01:00 | 2024-06-25T20:23:15+02:00 | 103245158 |
| turbot/steampipe:0.21.4 | active   | kaidaguerre            | 2024-01-23T13:28:51+01:00 | 2024-09-03T00:09:18+02:00 | 103435639 |
+-------------------------+----------+------------------------+---------------------------+---------------------------+-----------+
```

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-dockerhub/pull/25
